name: mfree-mumag-gpu
channels:
  - set3mah
  - conda-forge
channel_priority: strict    
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pyamg
  - meshio
  - meshpy
  - neper
  - povray
  - pip
  - pip:
      - jax[cuda12]
      - jaxopt
