
name: mfree-mumag-cpu
channels:
  - set3mah
  - conda-forge
channel_priority: strict
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pyamg
  - meshio
  - meshpy
  - neper
  - povray
  - pip
  - pip:
      - jax
      - jaxopt
