[workspace]
authors = ["HoWilgh <wilfried.hortschitz@donau-uni.ac.at>"]
channels = ["conda-forge", "set3mah"]
name = "mammos-mumag-matrixfree"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
pip = ">=25.2,<26"
numpy = "*"
scipy = "*"
matplotlib = "*"
pyamg = ">=5.3.0,<6"
meshio = ">=5.3.5,<6"
meshpy = ">=2025.1.1,<2026"
neper = ">=4.6.0,<5"
#neper = ">=4.1.2,<5"
#neper = ">=4.1.2,<5"
povray = ">=3.7.0.8,<4"
gmsh = ">=4.8.0,<5"
mammos-entity = ">=0.11.1,<0.12"
mammos-analysis = ">=0.3.0,<0.5"

[pypi-dependencies]
#jax = { version = ">=0.8.1, <0.9", extras = ["cuda12"] }
jax = { version = "*", extras = ["cuda12"] }
jaxopt = "*"
