[workspace]
authors = ["HoWilgh <wilfried.hortschitz@donau-uni.ac.at>"]
channels = ["conda-forge", "set3mah"]
name = "mammos-mumag-matrixfree"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
pip = ">=25.2,<26"
numpy = "*"
scipy = "*"
matplotlib = "*"
pyamg = ">=5.3.0,<6"
meshio = ">=5.3.5,<6"
meshpy = ">=2025.1.1,<2026"
neper = ">=4.1.2,<5"
povray = ">=3.7.0.8,<4"
gmsh = ">=4.12.2,<5"

[pypi-dependencies]
jax = { version = ">=0.8.1, <0.9", extras = ["cuda12"] }
jaxopt = ">=0.8.5, <0.9"
